{"uuid":"20034bc1-20ff-4fb7-8d3e-f7fe5c19c9fd","name":"Вход с неверным паролем","historyId":"d503077cdc6811bc372ffef5ded2845a:8e5078d1282f6e617a426e16a475fc5f","status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Неверный пароль\"\nReceived message:   \"Неверный логин или пароль\"\n\n      33 |             const msg = `Неверный пароль`;\n      34 |             logger.error(msg);\n    > 35 |             throw new CredentialsError();\n         |                   ^\n      36 |         }\n      37 |\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:35:19)","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Неверный пароль\"\nReceived message:   \"Неверный логин или пароль\"\n\n      33 |             const msg = `Неверный пароль`;\n      34 |             logger.error(msg);\n    > 35 |             throw new CredentialsError();\n         |                   ^\n      36 |         }\n      37 |\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:35:19)\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:113:49\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967257427,"name":"Подготовка тестовых данных","stop":1760967257428},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967257428,"name":"Выполнение команды входа","stop":1760967257428},{"status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Неверный пароль\"\nReceived message:   \"Неверный логин или пароль\"\n\n      33 |             const msg = `Неверный пароль`;\n      34 |             logger.error(msg);\n    > 35 |             throw new CredentialsError();\n         |                   ^\n      36 |         }\n      37 |\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:35:19)","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Неверный пароль\"\nReceived message:   \"Неверный логин или пароль\"\n\n      33 |             const msg = `Неверный пароль`;\n      34 |             logger.error(msg);\n    > 35 |             throw new CredentialsError();\n         |                   ^\n      36 |         }\n      37 |\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:35:19)\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:113:49\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967257429,"name":"Проверка ошибки неверного пароля","stop":1760967257456}],"attachments":[],"parameters":[{"name":"login","value":"new_login"},{"name":"Введённый пароль","value":"password"},{"name":"Пароль из БД","value":"wrongpassword"},{"name":"Текст ошибки","value":"Неверный пароль"}],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"jest"},{"name":"package","value":"src.__tests__.unit-tests.authperson.test.ts"},{"name":"host","value":"LAPTOP-7FFNEF67"},{"name":"thread","value":"1"},{"name":"parentSuite","value":"Вход и регистрация пользователя"}],"links":[],"start":1760967257424,"fullName":"src/__tests__/unit-tests/authperson.test.ts#Вход и регистрация пользователя Вход с неверным паролем","titlePath":["src","__tests__","unit-tests","authperson.test.ts","Вход и регистрация пользователя"],"testCaseId":"d503077cdc6811bc372ffef5ded2845a","stop":1760967257457}