{"uuid":"53d013cd-c3bb-413a-a6e5-21ed3390bacc","name":"Неуспешная регистрация из-за занятого логина","historyId":"2baa180c102203e85a9aa383782097c7:d1917805761245fd795d3d08f51c75ac","status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected constructor: BusyLoginError\nReceived constructor: TypeError\n\nReceived message: \"Cannot destructure property 'login_exists' of 'checkResult.rows[0]' as it is undefined.\"\n\n      59 |             const checkResult = await client.query(checkQuery, [login, name]);\n      60 |             console.log(checkResult)\n    > 61 |             const { login_exists, name_exists } = checkResult.rows[0];\n         |                     ^\n      62 |\n      63 |             if (login_exists && name_exists) {\n      64 |                 await client.query('ROLLBACK');\n\n      at PersonRepository.create (src/Repository/Implementations/PersonRepository.ts:61:21)\n      at src/__tests__/unit-tests/authperson.test.ts:246:13","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected constructor: BusyLoginError\nReceived constructor: TypeError\n\nReceived message: \"Cannot destructure property 'login_exists' of 'checkResult.rows[0]' as it is undefined.\"\n\n      59 |             const checkResult = await client.query(checkQuery, [login, name]);\n      60 |             console.log(checkResult)\n    > 61 |             const { login_exists, name_exists } = checkResult.rows[0];\n         |                     ^\n      62 |\n      63 |             if (login_exists && name_exists) {\n      64 |                 await client.query('ROLLBACK');\n\n      at PersonRepository.create (src/Repository/Implementations/PersonRepository.ts:61:21)\n      at src/__tests__/unit-tests/authperson.test.ts:246:13\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:251:24\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760969118204,"name":"Подготовка тестовых данных","stop":1760969118205},{"status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected constructor: BusyLoginError\nReceived constructor: TypeError\n\nReceived message: \"Cannot destructure property 'login_exists' of 'checkResult.rows[0]' as it is undefined.\"\n\n      59 |             const checkResult = await client.query(checkQuery, [login, name]);\n      60 |             console.log(checkResult)\n    > 61 |             const { login_exists, name_exists } = checkResult.rows[0];\n         |                     ^\n      62 |\n      63 |             if (login_exists && name_exists) {\n      64 |                 await client.query('ROLLBACK');\n\n      at PersonRepository.create (src/Repository/Implementations/PersonRepository.ts:61:21)\n      at src/__tests__/unit-tests/authperson.test.ts:246:13","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected constructor: BusyLoginError\nReceived constructor: TypeError\n\nReceived message: \"Cannot destructure property 'login_exists' of 'checkResult.rows[0]' as it is undefined.\"\n\n      59 |             const checkResult = await client.query(checkQuery, [login, name]);\n      60 |             console.log(checkResult)\n    > 61 |             const { login_exists, name_exists } = checkResult.rows[0];\n         |                     ^\n      62 |\n      63 |             if (login_exists && name_exists) {\n      64 |                 await client.query('ROLLBACK');\n\n      at PersonRepository.create (src/Repository/Implementations/PersonRepository.ts:61:21)\n      at src/__tests__/unit-tests/authperson.test.ts:246:13\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:251:24\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760969118205,"name":"Выполнение команды регистрации и проверка ошибки","stop":1760969118221}],"attachments":[],"parameters":[{"name":"login","value":"new_login"},{"name":"password","value":"password"},{"name":"name","value":"name"},{"name":"role","value":"1"}],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"jest"},{"name":"package","value":"src.__tests__.unit-tests.authperson.test.ts"},{"name":"host","value":"LAPTOP-7FFNEF67"},{"name":"thread","value":"1"},{"name":"parentSuite","value":"Вход и регистрация пользователя"}],"links":[],"start":1760969118193,"fullName":"src/__tests__/unit-tests/authperson.test.ts#Вход и регистрация пользователя Неуспешная регистрация из-за занятого логина","titlePath":["src","__tests__","unit-tests","authperson.test.ts","Вход и регистрация пользователя"],"testCaseId":"2baa180c102203e85a9aa383782097c7","stop":1760969118229}